[project]
name = "hello-world"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0.0"
dependencies = [
    "aws-lambda-powertools (>=3.13.0,<4.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "boto3 (>=1.38.33,<2.0.0)",
    "types-boto3[dynamodb,iot] (>=1.38.36,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
